# Generated by Django 4.1.2 on 2022-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
