# Generated by Django 4.1.2 on 2022-10-28 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_payment_amount_alter_payment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='video',
            name='course_Video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/', verbose_name=''),
            preserve_default=False,
        ),
    ]
