# Generated by Django 4.1.2 on 2022-10-28 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_video_youtube_id_video_course_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course_Video',
        ),
        migrations.AddField(
            model_name='course',
            name='course_Video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_urls',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
