# Generated by Django 4.1.2 on 2022-10-29 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_video_course_video_course_course_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_Video',
        ),
        migrations.AddField(
            model_name='course',
            name='video_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
