# Generated by Django 4.1.2 on 2022-10-30 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_course_course_video_course_video_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='plan_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
