# Generated by Django 3.2.16 on 2022-11-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_course_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
